module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/BFBZC0sOKxC6IiwKxpNm9m?mode=gi_t',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/w3u2zn.png',
    NEWSLETTER_JID: '120363401269012709@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'MAD MAX',
    OWNER_NAME: 'unkown',
    OWNER_NUMBER: '254769769295,254795753256',
    BOT_VERSION: '5.0.0',
    BOT_FOOTER: '> CYBER DARK TECH',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb5ytZEE50UbwV7xBv1k',
};
